// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package internal

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Feed struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	Name      string
	Url       string
	UserID    pgtype.UUID
}

type User struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	Name      string
	ApiKey    string
}
